{% set name = "librepo" %}
{% set version = "1.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rpm-software-management/librepo/archive/{{ version }}.tar.gz
  sha256: 16e4158d6ce8a8536cc80dc327efb4ad53acf9181175b80cb9ef17cbda53cb8f

build:
  number: 0
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x' ) }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
    - pkg-config
  host:
    - libcurl
    - gpgme
    - attr
    - openssl
    - expat
    - glib
    - check
    - zchunk  # [linux]
    - libxml2
    - zstd
    - python

outputs:
  - name: librepo
    files:
      - lib/librepo*
      - lib/pkgconfig/librepo*
      - include/librepo/*
    test:
      commands:
        - test -d ${PREFIX}/include/librepo  # [unix]
        - test -f ${PREFIX}/include/librepo/librepo.h  # [unix]
        - test -f ${PREFIX}/include/librepo/checksum.h  # [unix]
        - test -f ${PREFIX}/lib/librepo${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/lib/pkgconfig/librepo.pc  # [unix]

  - name: py-librepo
    files:
      - lib/python*/site-packages/librepo/**
    requirements:
      build:
        - cmake
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('librepo', exact=True) }}
        - libcurl
        - gpgme
        - attr
        - openssl
        - expat
        - glib
        - check
        - zchunk
        - libxml2
        - zstd
        - python
      run:
        - {{ pin_subpackage('librepo', exact=True) }}
        - python
    test:
      imports:
        - librepo

about:
  home: https://github.com/rpm-software-management/librepo
  license: LGPL-2.1
  license_family: GPL
  license_file: COPYING
  summary: A library providing C and Python (libcURL like) API for downloading repository metadata and packages
  doc_url: https://rpm-software-management.github.io/librepo

extra:
  recipe-maintainers:
    - wolfv
    - JohanMabille
    - SylvainCorlay
